"""Export the combined schema + metadata into stable formats.

JSON is the primary format. Its shape is versioned (`$schema_version`) so
downstream consumers (docs generators, LLM training pipelines) can depend on it.
"""

from __future__ import annotations

import json
from typing import Any

from ..introspect.schema_model import Schema

JSON_SCHEMA_VERSION = "1.0"


def _decode_tags(raw: str | None) -> list[str]:
    if not raw:
        return []
    try:
        val = json.loads(raw)
        if isinstance(val, list):
            return [str(v) for v in val]
    except json.JSONDecodeError:
        pass
    return []


def to_json(
    schema: Schema,
    table_meta: list[dict],
    column_meta: list[dict],
    *,
    database_name: str,
    include_excluded: bool = False,
) -> dict[str, Any]:
    by_table: dict[tuple[str, str], dict] = {
        (m["schema_name"], m["table_name"]): m for m in table_meta
    }
    by_column: dict[tuple[str, str, str], dict] = {
        (m["schema_name"], m["table_name"], m["column_name"]): m for m in column_meta
    }

    tables: list[dict] = []
    for t in schema.table_list():
        tm = by_table.get((t.schema, t.name), {}) or {}
        if tm and not tm.get("llm_include", 1) and not include_excluded:
            continue
        cols_out: list[dict] = []
        for c in t.columns:
            cm = by_column.get((t.schema, t.name, c.name), {}) or {}
            if cm and not cm.get("llm_include", 1) and not include_excluded:
                continue
            cols_out.append(
                {
                    "name": c.name,
                    "data_type": c.type_string(),
                    "nullable": c.is_nullable,
                    "identity": c.is_identity,
                    "computed": c.is_computed,
                    "default": c.default_definition,
                    "description": cm.get("description") or c.description,
                    "sample_values": cm.get("sample_values"),
                    "sensitivity": cm.get("sensitivity"),
                    "glossary_term": cm.get("glossary_term"),
                    "tags": _decode_tags(cm.get("tags_json")),
                }
            )
        tables.append(
            {
                "schema": t.schema,
                "name": t.name,
                "fqname": t.fqname,
                "kind": "view" if t.is_view else "table",
                "description": tm.get("description") or t.description,
                "owner": tm.get("owner"),
                "domain": tm.get("domain"),
                "source_of_truth_url": tm.get("source_of_truth_url"),
                "tags": _decode_tags(tm.get("tags_json")),
                "primary_key": t.primary_key.columns if t.primary_key else [],
                "unique_constraints": [u.columns for u in t.unique_constraints],
                "foreign_keys": [
                    {
                        "name": fk.name,
                        "columns": fk.columns,
                        "references": {
                            "table": f"{fk.ref_schema}.{fk.ref_table}",
                            "columns": fk.ref_columns,
                        },
                        "on_delete": fk.on_delete,
                        "on_update": fk.on_update,
                    }
                    for fk in t.foreign_keys
                ],
                "indexes": [
                    {
                        "name": i.name,
                        "type": i.type_desc,
                        "unique": i.is_unique,
                        "key_columns": i.key_columns,
                        "included_columns": i.included_columns,
                        "filter": i.filter_definition,
                    }
                    for i in t.indexes
                ],
                "row_count": t.row_count,
                "columns": cols_out,
            }
        )

    return {
        "$schema_version": JSON_SCHEMA_VERSION,
        "database": database_name,
        "tables": tables,
    }


def to_markdown(json_doc: dict[str, Any]) -> str:
    lines: list[str] = [
        f"# {json_doc.get('database', 'database')} — schema documentation",
        "",
        f"_generated by sqlutil (schema version {json_doc.get('$schema_version', '?')})_",
        "",
    ]
    for t in json_doc["tables"]:
        lines.append(f"## `{t['fqname']}`")
        if t.get("description"):
            lines.append("")
            lines.append(t["description"])
        lines.append("")
        lines.append("| Column | Type | Nullable | Description | Tags |")
        lines.append("|---|---|---|---|---|")
        for c in t["columns"]:
            tags = ", ".join(c.get("tags") or [])
            desc = (c.get("description") or "").replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| `{c['name']}` | `{c['data_type']}` | {'yes' if c['nullable'] else 'no'} | {desc} | {tags} |"
            )
        if t.get("foreign_keys"):
            lines.append("")
            lines.append("**Foreign keys**")
            for fk in t["foreign_keys"]:
                cols = ", ".join(fk["columns"])
                ref = fk["references"]
                ref_cols = ", ".join(ref["columns"])
                lines.append(f"- `{cols}` → `{ref['table']}`({ref_cols})")
        lines.append("")
    return "\n".join(lines)
