define([], function () {
  return {
    PropertyPaneDescription: 'Configure the SharePoint lists and fields the Competency Matrix reads from. Field settings use internal names.',
    GeneralGroupName: 'General',
    CompetenciesGroupName: 'Competencies list',
    StaffGroupName: 'Team list',
    RbacGroupName: 'Onboarding access (RBAC)',
    TitleFieldLabel: 'Web part title',
    CompetenciesListFieldLabel: 'List title',
    LeadFieldLabel: 'Lead field internal name',
    CompetencyDescriptionFieldLabel: 'Description field internal name',
    StaffListFieldLabel: 'List title',
    StaffPersonFieldLabel: 'Person field internal name',
    CompetencyLookupFieldLabel: 'Competency lookup field internal name',
    StartDateFieldLabel: 'Start date field name',
    EndDateFieldLabel: 'End date field name',
    RbacListFieldLabel: 'List title',
    RbacUserFieldLabel: 'User field internal name',
    RbacFlagFieldLabel: 'Onboarding flag field internal name',
    OptionalFieldDescription: 'Optional - leave empty if the list does not have this field.',
    DefaultTitle: 'Competency Matrix',
    SearchPlaceholder: 'Search for a person...',
    FilterLabel: 'Filter by competency',
    AllCompetenciesOption: 'All competencies',
    LoadingText: 'Loading competencies and team...',
    LoadErrorText: 'Something went wrong while loading data. Check the web part configuration (list titles and field internal names).',
    LeadSectionLabel: 'Lead',
    LeadsSectionLabel: 'Leads',
    TeamSectionLabel: 'Team',
    NoLeadText: 'No lead assigned',
    NoMembersText: 'No team members yet',
    NoCompetenciesTitle: 'Nothing to show',
    NoCompetenciesText: 'No competencies found. Check the configured list titles in the web part properties.',
    NoSearchResultsTitle: 'No matches',
    NoSearchResultsText: 'No people or competencies match your search.',
    LeadBadgeText: 'Lead',
    MatchFoundLabel: 'person found',
    MatchesFoundLabel: 'people found',
    CompetenciesCountLabel: 'competencies',
    PeopleCountLabel: 'people',
    PersonCountSuffix: 'person',
    PeopleCountSuffix: 'people',
    UpcomingBadgePrefix: 'from',
    OnboardButtonText: 'Onboard staff',
    OffboardButtonText: 'Offboard staff',
    OnboardPanelTitle: 'Onboard staff',
    OffboardPanelTitle: 'Offboard staff',
    PersonPickerLabel: 'Person',
    PeopleSuggestionsHeaderText: 'Matching people',
    NoPeopleFoundText: 'No people found',
    CompetenciesPickerLabel: 'Competencies',
    CompetenciesPickerPlaceholder: 'Select one or more competencies',
    StartDateLabel: 'Start date',
    EndDateLabel: 'End date (last day)',
    OnboardSubmitText: 'Onboard',
    OffboardSubmitText: 'Offboard',
    CancelButtonText: 'Cancel',
    SavingText: 'Saving...',
    OnboardMissingFieldsText: 'Pick a person and at least one competency.',
    OffboardMissingFieldsText: 'Pick a team member to offboard.',
    OnboardSuccessText: '{0} has been onboarded.',
    OffboardSuccessText: '{0} has been offboarded. They will disappear from the matrix after their end date.',
    ActionErrorText: 'The change could not be saved.',
    OnboardHintText: 'One entry per selected competency is created in the team list with the chosen start date.',
    OffboardHintText: 'The end date is stamped on all of this person’s entries. They stay visible until that date has passed.',
    OffboardPersonLabel: 'Team member',
    OffboardPersonPlaceholder: 'Select a team member',
    OffboardAffectedLabel: 'Will be offboarded from',
    NoStaffToOffboardText: 'There are no active team members to offboard.'
  };
});
