define([], function () {
  return {
    PropertyPaneDescription: 'Configure the SharePoint lists and fields the Competency Matrix reads from.',
    GeneralGroupName: 'General',
    CompetenciesGroupName: 'Competencies list',
    StaffGroupName: 'Staff list',
    TitleFieldLabel: 'Web part title',
    CompetenciesListFieldLabel: 'List title',
    CompetencyDescriptionFieldLabel: 'Description field internal name',
    StaffListFieldLabel: 'List title',
    StaffNameFieldLabel: 'Staff name field internal name',
    StaffNameIsPersonLabel: 'Staff name field is a Person field',
    StaffNameIsPersonOn: 'Person field',
    StaffNameIsPersonOff: 'Text field',
    CompetencyLookupFieldLabel: 'Competency lookup field internal name',
    RoleFieldLabel: 'Role field internal name',
    LeaderRoleValueLabel: 'Role value that marks a leader',
    OptionalFieldDescription: 'Optional - leave empty if the list does not have this field.',
    DefaultTitle: 'Competency Matrix',
    SearchPlaceholder: 'Search for a person...',
    FilterLabel: 'Filter by competency',
    AllCompetenciesOption: 'All competencies',
    LoadingText: 'Loading competencies and staff...',
    LoadErrorText: 'Something went wrong while loading data. Check the web part configuration (list titles and field internal names).',
    LeadersSectionLabel: 'Leaders',
    StaffSectionLabel: 'Staff',
    NoLeadersText: 'No leaders assigned',
    NoStaffText: 'No staff assigned',
    NoCompetenciesText: 'No competencies found. Check the configured list titles in the web part properties.',
    NoSearchResultsText: 'No people or competencies match your search.',
    NoCompetencyForPersonText: 'not tagged to any competency',
    LeaderBadgeText: 'Leader',
    CompetenciesCountLabel: 'competencies',
    StaffCountLabel: 'staff members'
  };
});
