define([], function () {
  return {
    PropertyPaneDescription: 'Configure the SharePoint lists and fields the Competency Matrix reads from. Field settings use internal names.',
    GeneralGroupName: 'General',
    CompetenciesGroupName: 'Competencies list',
    StaffGroupName: 'Team list',
    TitleFieldLabel: 'Web part title',
    CompetenciesListFieldLabel: 'List title',
    LeadFieldLabel: 'Lead field internal name',
    CompetencyDescriptionFieldLabel: 'Description field internal name',
    StaffListFieldLabel: 'List title',
    StaffPersonFieldLabel: 'Person field internal name',
    CompetencyLookupFieldLabel: 'Competency lookup field internal name',
    OptionalFieldDescription: 'Optional - leave empty if the list does not have this field.',
    DefaultTitle: 'Competency Matrix',
    SearchPlaceholder: 'Search for a person...',
    FilterLabel: 'Filter by competency',
    AllCompetenciesOption: 'All competencies',
    LoadingText: 'Loading competencies and team...',
    LoadErrorText: 'Something went wrong while loading data. Check the web part configuration (list titles and field internal names).',
    LeadSectionLabel: 'Lead',
    LeadsSectionLabel: 'Leads',
    TeamSectionLabel: 'Team',
    NoLeadText: 'No lead assigned',
    NoMembersText: 'No team members yet',
    NoCompetenciesTitle: 'Nothing to show',
    NoCompetenciesText: 'No competencies found. Check the configured list titles in the web part properties.',
    NoSearchResultsTitle: 'No matches',
    NoSearchResultsText: 'No people or competencies match your search.',
    LeadBadgeText: 'Lead',
    MatchFoundLabel: 'person found',
    MatchesFoundLabel: 'people found',
    CompetenciesCountLabel: 'competencies',
    PeopleCountLabel: 'people',
    PersonCountSuffix: 'person',
    PeopleCountSuffix: 'people'
  };
});
