declare interface ICompetencyMatrixWebPartStrings {
  PropertyPaneDescription: string;
  GeneralGroupName: string;
  CompetenciesGroupName: string;
  StaffGroupName: string;
  RbacGroupName: string;
  TitleFieldLabel: string;
  CompetenciesListFieldLabel: string;
  LeadFieldLabel: string;
  CompetencyDescriptionFieldLabel: string;
  StaffListFieldLabel: string;
  StaffPersonFieldLabel: string;
  CompetencyLookupFieldLabel: string;
  StartDateFieldLabel: string;
  EndDateFieldLabel: string;
  RbacListFieldLabel: string;
  RbacUserFieldLabel: string;
  RbacFlagFieldLabel: string;
  OptionalFieldDescription: string;
  DefaultTitle: string;
  SearchPlaceholder: string;
  FilterLabel: string;
  AllCompetenciesOption: string;
  LoadingText: string;
  LoadErrorText: string;
  LeadSectionLabel: string;
  LeadsSectionLabel: string;
  TeamSectionLabel: string;
  NoLeadText: string;
  NoMembersText: string;
  NoCompetenciesTitle: string;
  NoCompetenciesText: string;
  NoSearchResultsTitle: string;
  NoSearchResultsText: string;
  LeadBadgeText: string;
  MatchFoundLabel: string;
  MatchesFoundLabel: string;
  CompetenciesCountLabel: string;
  PeopleCountLabel: string;
  PersonCountSuffix: string;
  PeopleCountSuffix: string;
  UpcomingBadgePrefix: string;
  OnboardButtonText: string;
  OffboardButtonText: string;
  OnboardPanelTitle: string;
  OffboardPanelTitle: string;
  PersonPickerLabel: string;
  PeopleSuggestionsHeaderText: string;
  NoPeopleFoundText: string;
  CompetenciesPickerLabel: string;
  CompetenciesPickerPlaceholder: string;
  StartDateLabel: string;
  EndDateLabel: string;
  OnboardSubmitText: string;
  OffboardSubmitText: string;
  CancelButtonText: string;
  SavingText: string;
  OnboardMissingFieldsText: string;
  OffboardMissingFieldsText: string;
  OnboardSuccessText: string;
  OffboardSuccessText: string;
  ActionErrorText: string;
  OnboardHintText: string;
  OffboardHintText: string;
  OffboardPersonLabel: string;
  OffboardPersonPlaceholder: string;
  OffboardAffectedLabel: string;
  NoStaffToOffboardText: string;
}

declare module 'CompetencyMatrixWebPartStrings' {
  const strings: ICompetencyMatrixWebPartStrings;
  export = strings;
}
